name: build-and-release

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-13, ubuntu-20.04, windows-2022]
        steps:
            - name: checkout repo
              uses: actions/checkout@v2
              with:
                submodules: recursive
            - name: Install git sdk
              if: ${{ matrix.os == 'windows-2022' }}
              uses: git-for-windows/setup-git-for-windows-sdk@v1
              with:
                flavor: full

            - name: download binary components
              run: ./make-dependencies.sh

            - name: Create Binary Windows
              if: ${{ matrix.os == 'windows-2022' }}
              run: make winapp

            - name: Create Binary Linux
              if: ${{ matrix.os == 'ubuntu-20.04' }}
              run: make linuxapp

            - name: Create Binary macOS
              if: ${{ matrix.os == 'macos-13' }}
              run: make macapp
              
            - name: upload result
              uses: actions/upload-artifact@v4
              with:
                name: build-${{ matrix.os }}
                path: dist/*

    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        if: github.event_name != 'pull_request' 
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              id: download
              with:
                path: ~/downloads

            - name: Create binary dir
              run: mkdir binary

            - name: Collect all artifacts
              run: find ${{steps.download.outputs.download-path}} -type f -exec mv {} binary \;

            - name: Display structure of downloaded files
              run: ls -R

            - name: Release result
              uses: marvinpinto/action-automatic-releases@v1.2.1
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: true
                  title: "Development Build"
                  files: |
                    binary/*
